sudo: required
dist: bionic
language: python
env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
  matrix:
    - ARCH=rpi
      GOIMG=resin/rpi-raspbian
      DOCKER_BUILD=mastermindg/docker-flow-proxy:rpi-${VERSION}
      DOCKERFILE=test.Dockerfile
services:
  - xvfb # X virtual framebuffer. Run the graphical application without display them while also having the ability to take screenshots.
  - docker
cache:
  directories:
    - /usr/share/t_system
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build --tag test -f test.Dockerfile .
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker push test
    fi
after_success:
  — coveralls
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
