sudo: required
language: python
env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
  matrix:
    - ARCH=rpi
      GOIMG=kutsudock/rpi-alpine-go
      DOCKER_BUILD=mastermindg/docker-flow-proxy:rpi-${VERSION}
      DOCKERFILE=Dockerfile
#virtualenv:
#    system_site_packages: true
services:
    - xvfb # X virtual framebuffer. Run the graphical application without display them while also having the ability to take screenshots.
    - docker
cache:
    directories:
        - /usr/share/t_system
#before_install:
#    - mysql -u root -e "CREATE DATABASE ava;"
install:
    - sudo ./install-dev.sh --no-model
    - sudo pip3 install pytest-faulthandler
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    # prepare qemu
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    # build image
    - docker build -t hypriot/rpi-raspbian .
    # test image
    - docker run hypriot/rpi-raspbian
    # push image
    - >
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
          docker tag hypriot/rpi-raspbian
          docker push hypriot/rpi-raspbian
          docker push hypriot/rpi-raspbian
        fi
    - python3 -m pytest --capture=sys
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
