#sudo: required
#dist: trusty
language: python
virtualenv:
    system_site_packages: true
services:
    - xvfb
cache:
    directories:
        - /usr/share/t_system
#before_install:
#    - mysql -u root -e "CREATE DATABASE ava;"
install:
    - sudo ./install-dev.sh --no-model
    - sudo pip3 install pytest-faulthandler
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - python3 -m pytest --capture=sys
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
